TimeSheet/Controllers/AdminController.cs
using System.Configuration;
using System.Web.Mvc;

namespace ProjectTimeSheet.Controllers
{
    public class AdminController : Controller
    {
        public DataAccess dataAccess = null;

        public AdminController()
        {
            dataAccess = new DataAccess(ConfigurationManager.ConnectionStrings["DbConnection"].ToString());
        }
        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.usercount = dataAccess.GetCountofUser();
            ViewBag.deptcount = dataAccess.GetCountofDepartment();
            ViewBag.taskcount = dataAccess.GetCountofTask();
            return View();
        }

        public ActionResult TimeSheetWeekly()
        {
            return PartialView(dataAccess.GetTimeSheetWeeklyDetails("092018"));
        }


    }
}

TimeSheet/Controllers/TaskController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace ProjectTimeSheet.Controllers
{
    public class TaskController : Controller
    {

        public DataAccess dataAccess = null;

        public TaskController()
        {
            dataAccess = new DataAccess(ConfigurationManager.ConnectionStrings["DbConnection"].ToString());
        }

        // GET: Task
        public ActionResult Index()
        {
            return View(dataAccess.GetListofTaskInfo());
        }

        // GET: Task/Create
        public ActionResult Create()
        {
            ViewBag.Departments = dataAccess.GetListofDepartmentInfo().Select(n => new SelectListItem() { Value = n.DepartmentId.ToString(), Text = n.Name });
            return View();
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                dataAccess.InsertTask(
                    new Models.Task()
                    {
                        Name = Request.Form["Name"],
                        DepartmentId = Request.Form["Department"],
                    });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int id)
        {
            var taskinfo = dataAccess.GetTaskInfobyId(id);
            ViewBag.Departments = dataAccess.GetListofDepartmentInfo().Select(n => new SelectListItem() { Value = n.DepartmentId.ToString(), Text = n.Name, Selected = (n.DepartmentId == Convert.ToInt32(taskinfo.Department)) });
            return View(taskinfo);
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                dataAccess.UpdateTask(
                    new Models.Task()
                    {
                        TaskId = id,
                        Name = Request.Form["Name"],
                        DepartmentId = Request.Form["Department"]
                    });
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int id)
        {
            return View(dataAccess.GetTaskInfobyId(id));
        }

        // POST: Task/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                dataAccess.DeleteTaskbyID(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TimeSheet/Controllers/UsersController.cs
using ProjectTimeSheet.Models;
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace ProjectTimeSheet.Controllers
{
    public class UsersController : Controller
    {
        public DataAccess dataAccess = null;

        public UsersController()
        {
            dataAccess = new DataAccess(ConfigurationManager.ConnectionStrings["DbConnection"].ToString());
        }
        // GET: Users
        public ActionResult Index()
        {
            return View(dataAccess.GetListofUsersDetails());
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.Departments = dataAccess.GetListofDepartmentInfo().Select(n => new SelectListItem() { Value = n.DepartmentId.ToString(), Text = n.Name });
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                dataAccess.InsertUser(
                    new User
                    {
                        UserName = Request.Form["UserName"],
                        EmailId = Request.Form["EmailId"],
                        EmpId = Convert.ToInt32(Request.Form["EmpId"]),
                        FullName = Request.Form["FullName"],
                        DepartmentId = Convert.ToInt32(Request.Form["DepartmentId"])
                    });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int id)
        {
            var userInfo = dataAccess.GetUserInfo(id);
            ViewBag.Departments = dataAccess.GetListofDepartmentInfo().Select(n => new SelectListItem() { Value = n.DepartmentId.ToString(), Text = n.Name, Selected = (n.DepartmentId == userInfo.DepartmentId) });
            return View(userInfo);
        }

        // POST: Users/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                dataAccess.UpdateUser(
                    new User()
                    {
                        UserId = id,
                        UserName = Request.Form["UserName"],
                        EmailId = Request.Form["EmailId"],
                        EmpId = Convert.ToInt32(Request.Form["EmpId"]),
                        FullName = Request.Form["FullName"],
                        DepartmentId = Convert.ToInt32(Request.Form["DepartmentId"])
                    });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {
            return View(dataAccess.GetUserInfo(id));
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                dataAccess.DeleteUserbyID(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TimeSheet/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <title>TimeSheet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>


<body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="@Url.Action("Index","Admin")">Time Sheet</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
    </nav>

    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Admin")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Users")">
                    <i class="fas fa-user-plus"></i>
                    <span>Users</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Task")">
                    <i class="fas fa-tasks"></i>
                    <span>Task</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Department")">
                    <i class="fas fa-laptop-code"></i>
                    <span>Department</span>
                </a>
            </li>
        </ul>
        <div id="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/sb-admin.min.js"></script>
</body>

</html>

TimeSheet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <title>TimeSheet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
    </style>

</head>
<body>

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="@Url.Action("Index","Home")">Time Sheet</a>
    </nav>
    <div id="content-wrapper">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
</body>
</html>